apiVersion: n9/v1alpha
kind: SLO
metadata:
  name: {name}
  displayName: "{displayName}"
  namespace: {namespace}
spec:
  description: "{description}"
  service: {service_name}
  indicator:
    metricSource: {datasource}
  budgetingMethod: Occurrences
  alertPolicies: []
